---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- hosts: all
  gather_facts: true
  roles:
    - base

# - name: configuration
#   hosts: all
#   gather_facts: false # remove later! speeds up testing
#   become: true

#   roles:
#     - base

- hosts: frontends
  gather_facts: true
  roles:
    - haproxy

# - name: deploy haproxy
#   hosts: frontends
#   gather_facts: false # remove later! speeds up testing
#   become: true

#   roles:
#     - haproxy

- hosts: apps
  gather_facts: true
  roles:
    - tomcat

# - name: deploy tomcat
#   hosts: apps
#   gather_facts: false
#   become: true
#   roles:
#     - tomcat
- hosts: appdbs
  gather_facts: true
  roles:
    - tomcat
# - name: deploy postgres
#   hosts: apps
#   gather_facts: false
#   become: true
#   hosts: appdbs
#   roles:
#     - pgsql
  
- hosts: apps
  gather_facts: true
  roles:
    - apache

# - name: deploy apache
#   hosts: apps
#   gather_facts: false
#   become: true
#   hosts: apps
#   role:
#     - apache
